#!/usr/bin/env bash


projectdir=$(dirname $0)


function usage
{
    cat "$projectdir/usage"
}

if [ $# -eq 0 ]; then
    usage
    exit
fi


case $1 in 
    "add") 
        "$projectdir/add.bash" $2
    ;;

    "read") # read next page
        "$projectdir/read.bash" $2
    ;;

    "rn") # read next page - shorthand for "read"
        "$projectdir/read.bash" $2
    ;;

    *) 
        echo "That command not exist"
        usage
    ;; 
esac
